version: "3.7"

services:
  app:
    build: 
      context: ./frontend
      target: 'develop-stage'
    ports:
      - "8080:8080"
    volumes:
      - './frontend/app/:/app'
    command:  "npm run serve"
    networks:
      - webnet

networks: 
  webnet: